{
 "title": "Adoptree métricas",
 "description": "Métricas HTTP y Básicas recolectadas con Prometheus",
 "tags": [ "Nestjs" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(nodejs_version_info, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Métricas HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duración de las peticiones por Bucket",
   "type": "timeseries",
   "description": "Peticiones HTTP agrupadas por diferentes intervalos (buckets) de duraciones para las solicitudes HTTP",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{path!=\"/metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request totales a Fincas",
   "type": "timeseries",
   "description": "Medición de las Request totales al Endpoint de Fincas",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "http_requests_total{method=\"GET\", path=\"/fincas\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request totales a Arboles",
   "type": "timeseries",
   "description": "Request Totales al Endpoint de Arboles",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "http_requests_total{method=\"GET\", path=\"/arboles\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Métricas Totales",
   "type": "timeseries",
   "description": "Metricas totales de la aplicación, tiene el path y el status",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "http_requests_total{path!=\"/metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duración media de las solicitudes HTTP",
   "type": "timeseries",
   "description": "Se obtiene la duración media de las solicitudes HTTP en los últimos 5 minutos",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Métodos POST",
   "type": "timeseries",
   "description": "Métodos POST en los últimos 20 minutos",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{method=\"POST\"}[20m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Métricas por defecto",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\"}[2m]) * 100",
       "legendFormat": "User CPU - {{instance}}"
      },
      {
       "expr": "irate(process_cpu_system_seconds_total{instance=~\"$instance\"}[2m]) * 100",
       "legendFormat": "Sys CPU - {{instance}}"
      }
     ]
    },
    {
     "title": "Event Loop Lag",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 10, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node.js Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(nodejs_version_info{instance=~\"$instance\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Process Restart Times",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Process Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "Process Memory - {{instance}}"
      },
      {
       "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap Total - {{instance}}"
      },
      {
       "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap Used - {{instance}}"
      },
      {
       "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "External Memory - {{instance}}"
      }
     ]
    },
    {
     "title": "Active Handlers/Requests Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
       "legendFormat": "Active Handler - {{instance}}"
      },
      {
       "expr": "nodejs_active_requests_total{instance=~\"$instance\"}",
       "legendFormat": "Active Request - {{instance}}"
      }
     ]
    },
    {
     "title": "Heap Total Detail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_space_size_total_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap Total - {{instance}} - {{space}}"
      }
     ]
    },
    {
     "title": "Heap Used Detail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap Used - {{instance}} - {{space}}"
      }
     ]
    },
    {
     "title": "Heap Available Detail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_space_size_available_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap Used - {{instance}} - {{space}}"
      }
     ]
    }
   ]
  }
 ]
}